### ISSUE TITLE
Cat example does not work in OS X Safari

### ISSUE THREAD

**Issue by ArthurClemens** [jsguy/mithril.animate#4]
Works fine in Firefox and Chrome, not in Safari. No error message, just nothing.

**Comment by jsguy** [comment]
Hmmm...  http://arstechnica.com/information-technology/2015/06/op-ed-safari-is-the-new-internet-explorer/

I'll see what I can do - might just need to add some prefixes for the animations :)

**Comment by jsguy** [comment]
@ArthurClemens This is now fixed, enjoy the spinning cats! :)

**Comment by ArthurClemens** [comment]
Looks good.
